name: Deploy Temporal en GitHub Pages

on:
  push:
    branches:
      - test 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Verificamos la version
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup de Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.4'
          extended: true

      - name: Construir el Sitio
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
